name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Release workflow
        run: echo "Release workflow not yet implemented" && exit 1
